version: '3.8'

services:
  # RabbitMQ сервис с веб-интерфейсом управления
  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification-rabbitmq
    ports:
      - "5672:5672"   # порт для взаимодействия с RabbitMQ
      - "15672:15672" # порт веб-интерфейса
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notification-network

  # MailHog для тестирования отправки email-уведомлений
  mailhog:
    image: mailhog/mailhog
    container_name: notification-mailhog
    ports:
      - "1025:1025" # SMTP порт
      - "8025:8025" # Веб-интерфейс
    networks:
      - notification-network

  # Сервис уведомлений
  notification-service:
    build:
      context: notification-service/
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE=notifications
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USERNAME=notifications@system.com
      - SMTP_PASSWORD=password
      - SMTP_SENDER=notifications@system.com
    depends_on:
      rabbitmq:
        condition: service_healthy
      mailhog:
        condition: service_started
    networks:
      - notification-network

volumes:
  rabbitmq_data:

networks:
  notification-network:
    driver: bridge
